In [1]:
import pandas as pd

In [2]:
submit_to_agent = pd.read_pickle('./data/submit_to_agent.p')

In [3]:
submit_to_agent = submit_to_agent.loc[submit_to_agent.reason=='not_response'].reset_index()

In [4]:
submit_to_agent

,index,_id,userId,full_name,datetime,reason,message
0,4130,5e98775b824e7610370d0c70,3201270586549884,Thanyarat Khemthong,2020-04-16T15:18:51.943501,not_response,ทำไม เข้าดูข้อมูลในไลน์ ไม่ได้คะ
1,4131,5e98775c824e7610370d0c71,3092422274149118,Surasak Netkoson,2020-04-16T15:18:52.754715,not_response,สวัสดีครับ ผมทำประกัน COVID ที่สาขา ชัยภูมิ ตั...
2,4132,5e98775d824e7610370d0c72,3135374296495783,วัชรพล จันทร์แดง,2020-04-16T15:18:53.537091,not_response,73ครึ่ง 7 3ครึ่ง
3,4133,5e98775e824e7610370d0c73,2669199253155565,Jintana Chusit,2020-04-16T15:18:54.317138,not_response,0616407309
4,4134,5e98775f824e7610370d0c74,3336621019698874,ตุ๊กกี้ หลี่,2020-04-16T15:18:55.131380,not_response,วันก่อนผมนำรถ จยยไปขอสินเชื่อ แต่ถูกปฏิเสธ เพร...
...,...,...,...,...,...,...,...
3832,12351,5ec4e07bac4f5c1d305fe65c,3100678436658802,หนุ่มอนุบาล สุดหล่อ,2020-05-20T07:47:07.656826,not_response,https://scontent.xx.fbcdn.net/v/t1.15752-9/968...
3833,12352,5ec4e111ac4f5c1d305fe65d,3126007527457002,นุชรี ทองโอ,2020-05-20T07:49:37.617887,not_response,
3834,12353,5ec4e16bac4f5c1d305fe66e,4749158108443717,Meree Meree,2020-05-20T07:51:07.027190,not_response,{{DLJingjai}}
3835,12354,5ec4e189ac4f5c1d305fe670,2939113419516575,ตีบ แดนไต้,2020-05-20T07:51:37.688190,not_response,
3836,12355,5ec4e297ac4f5c1d305fe69b,2932202820207473,Sayamol Taprangsee,2020-05-20T07:56:07.127719,not_response,{{ถูกต้อง}}

In [9]:
df = submit_to_agent

In [10]:
df

,index,_id,userId,full_name,datetime,reason,message
0,4130,5e98775b824e7610370d0c70,3201270586549884,Thanyarat Khemthong,2020-04-16T15:18:51.943501,not_response,ทำไม เข้าดูข้อมูลในไลน์ ไม่ได้คะ
1,4131,5e98775c824e7610370d0c71,3092422274149118,Surasak Netkoson,2020-04-16T15:18:52.754715,not_response,สวัสดีครับ ผมทำประกัน COVID ที่สาขา ชัยภูมิ ตั...
2,4132,5e98775d824e7610370d0c72,3135374296495783,วัชรพล จันทร์แดง,2020-04-16T15:18:53.537091,not_response,73ครึ่ง 7 3ครึ่ง
3,4133,5e98775e824e7610370d0c73,2669199253155565,Jintana Chusit,2020-04-16T15:18:54.317138,not_response,0616407309
4,4134,5e98775f824e7610370d0c74,3336621019698874,ตุ๊กกี้ หลี่,2020-04-16T15:18:55.131380,not_response,วันก่อนผมนำรถ จยยไปขอสินเชื่อ แต่ถูกปฏิเสธ เพร...
...,...,...,...,...,...,...,...
3832,12351,5ec4e07bac4f5c1d305fe65c,3100678436658802,หนุ่มอนุบาล สุดหล่อ,2020-05-20T07:47:07.656826,not_response,https://scontent.xx.fbcdn.net/v/t1.15752-9/968...
3833,12352,5ec4e111ac4f5c1d305fe65d,3126007527457002,นุชรี ทองโอ,2020-05-20T07:49:37.617887,not_response,
3834,12353,5ec4e16bac4f5c1d305fe66e,4749158108443717,Meree Meree,2020-05-20T07:51:07.027190,not_response,{{DLJingjai}}
3835,12354,5ec4e189ac4f5c1d305fe670,2939113419516575,ตีบ แดนไต้,2020-05-20T07:51:37.688190,not_response,
3836,12355,5ec4e297ac4f5c1d305fe69b,2932202820207473,Sayamol Taprangsee,2020-05-20T07:56:07.127719,not_response,{{ถูกต้อง}}

In [11]:
# Clean undesired text
def clean_text_1(text):
    '''Make text lowercase, remove text in square brackets, remove punctuation and remove words containing numbers.'''
    text = text.lower()
    text = re.sub('[.?]', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('[‘’“”…]', '', text)
    text = re.sub('\n', '', text)
    text = re.sub('[0-9]{1,10}', '', text)
    text = re.sub('นะ|น่ะ|น่า|น้า','',text)
    text = re.sub('คะ|ค่ะ|ค่า|คระ|คร่ะ|คร๊|ค๊|คร้า','',text)
    text = re.sub('ครับ|คับ|คั้บ|ค้าบ|คัฟ|คร้าบ|คาฟ|ค้าฟ|ฮะ|ฮับ|ฮ้าฟ','',text)
    text = re.sub('จ้า|จ้ะ|จ๊ะ','',text)
    text = re.sub('หน่อย|น่อย','',text)
    text = re.sub('สวัสดี|หวัดดี','',text)
    text = re.sub('ของ','',text)
    # ลบ text ที่อยู่ในวงเล็บ <> ทั้งหมด
    text = re.sub(r'<.?>','', text)
    # ลบ hashtag
    text = re.sub(r'#','',text)
    # ลบ separator เช่น \n \t
    text = ' '.join(text.split())
    text = re.sub('สนใจ','',text)
    text = re.sub('อยากทราบว่า|อยากทราบ','',text)
    text = re.sub('รบกวนสอบถาม|ขอสอบถาม|สอบถาม','',text)
    text = re.sub('ปี','',text)
    text = re.sub('ขอบคุณ','',text)
    text = re.sub('ขอโทษ|ขอโทด','',text)
    text = re.sub('ขอ','',text)
    text = re.sub('ชั้น','',text)
    text = re.sub('เท่าไร|เท่าไหร่|เท่าหรั่ย|เท่าใด|เท่ารัย','',text)
    return text

In [12]:
def remove_digits(text):
    output = re.sub(r'\d+', '', text)
    return output

In [13]:
def remove_emoji(string):
    emoji_pattern = re.compile("["
                               u"\U0001F600-\U0001F64F"  # emoticons
                               u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                               u"\U0001F680-\U0001F6FF"  # transport & map symbols
                               u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                               u"\U00002500-\U00002BEF"  # chinese char
                               u"\U00002702-\U000027B0"
                               u"\U00002702-\U000027B0"
                               u"\U000024C2-\U0001F251"
                               u"\U0001f926-\U0001f937"
                               u"\U00010000-\U0010ffff"
                               u"\u2640-\u2642"
                               u"\u2600-\u2B55"
                               u"\u200d"
                               u"\u23cf"
                               u"\u23e9"
                               u"\u231a"
                               u"\ufe0f"  # dingbats
                               u"\u3030"
                               "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', string)

In [14]:
# Create new column to store the required string for further process
def clean_text_full(df):
    df = df.groupby(['userId'])['message'].apply(','.join).reset_index()
    df['message'] = df['message'].apply(lambda x: clean_text_1(x))
    df['message'] = df['message'].apply(lambda x: remove_emoji(x))
    df['message'] = df['message'].apply(lambda x: remove_digits(x))
    return df

In [23]:
df_new = df.groupby(['userId'])['message'].apply(','.join).reset_index()

In [24]:
df_new

                userId                                            message
0     1208159505978052                               อ่อ  วันนี้วันแรงงาน
1     1210709652387694                                        -,-,-,-,-,-
2     1267691383355577                                    ที่สนใจ,ที่สนใจ
3     1306377109441465  {{ค้นหาสาขา3}},1200ค่ะ,20000บาทค่ะ,{{ถูกต้อง}}...
4     1326415084040701                                                  ,
...                ...                                                ...
2412  4471413272884522                                     จ่ายบัตรน่ะค่ะ
2413  4474571902560282                                   1747082232269695
2414  4545438028815139                                        ระบุจังหวัด
2415  4749158108443717                                      {{DLJingjai}}
2416  4897828090270848                                                -,-

[2417 rows x 2 columns]